version: '3.8'
services:
  core:
    hostname: xian-stack
    build: 
      context: .
      dockerfile: ./docker/core.Dockerfile
    volumes:
      - ./xian-core:/usr/src/app/xian-core
      - ./xian-contracting:/usr/src/app/xian-core/xian-contracting
      - ./.cometbft:/root/.cometbft
    stdin_open: true
    tty: true
    command: >
    ports:
      - "26657:26657"
      - "26656:26656"
      - "26657:26657"
      bash -c "pip install -e ./xian-core && pip install -e ./xian-core/xian-contracting && tail -f /dev/null"

