version: '3.8'

networks:
  xian-net:
    internal: false  # Allow internet access for package installation
  xian-db:
    internal: true   # Keep database isolated

services:
  core:
    hostname: xian-stack-dev
    build: 
      dockerfile: ./docker/core-dev.Dockerfile  
    networks:
      - xian-net
      - xian-db
    command: >
      bash -c "pip install -e ./xian-core && pip install -e ./xian-core/xian-contracting && tail -f /dev/null"
