version: '3.8'

networks:
  xian-internal:
    internal: true

services:
  core:
    hostname: xian-stack-dev
    build: 
      dockerfile: ./docker/core-dev.Dockerfile  
    networks:
      - xian-internal
    command: >
      bash -c "pip install -e ./xian-core && pip install -e ./xian-core/xian-contracting && tail -f /dev/null"
