version: '3.8'
services:
  core:
    hostname: xian-stack-dev
    build: 
      dockerfile: ./docker/core-dev.Dockerfile
    command: >
      bash -c "pip install -e ./xian-core && pip install -e ./xian-core/xian-contracting && tail -f /dev/null"