version: '3.8'

networks:
  xian-net:
    internal: false  # Allow internet access for package installation
  xian-db:
    internal: true   # Keep database isolated

services:
  core:
    restart: always
    hostname: xian-stack
    build: 
      context: .
      dockerfile: ./docker/core.Dockerfile
    volumes:
      - ./xian-core:/usr/src/app/xian-core
      - ./xian-contracting:/usr/src/app/xian-core/xian-contracting
      - ./.cometbft:/root/.cometbft
    stdin_open: true
    tty: true
    networks:
      - xian-net
      - xian-db
    ports:
      - "26657:26657"
      - "26656:26656"
      - "26660:26660"
    # network_mode: "host"
    command: >
      bash -c "pip install -e ./xian-core && pip install -e ./xian-core/xian-contracting && tail -f /dev/null"
